# Setup
title:               Computer Algorithm
tagline:             'Han Kyunghwan'
description:         '컴퓨터 알고리즘 정리를 위한 사이트.'
url:                 https://hankom.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty
future: true

# About/contact
author:
  name:              한경환
  url:               https://none
  email:             pomen4444@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

theme: jekyll-theme-architect
